### ISSUE TITLE
API Docs and DB Diagram

### ISSUE THREAD

**Issue by AnthonyBronca** [Johney141/Tamriel-Retreats#1]
# API Docs:
Please make sure to adjust the routes throughout the API docs. I added a few suggested areas within the docs that need to be updated, however, I suspect a lot of the routes need to be updated.
Please reach out if you need assistance with RESTful naming conventions and how to proceed.

## Tasks:
- [x] Add DB Diagram reference to top of DB Diagram
- [x] Update Get the Current User route to follow the table name “Users”
- [x] Update Create a Spot route to follow RESTFUL naming convention
- [x] Update Add an Image to a Spot route to follow RESTFUL naming convention
- [x] Adjust Delete a Spot route to follow RESTFUL naming convention
- [x] Update Get all Reviews of Current User to follow RESTFUL naming convention
- [x] Update Add an Image to a Review based on Review's Id To follow RESTFUL naming convention
- [x] Adjust all other routes to follow RESTFUL

# DB Diagram:
Please make sure to complete a DB Diagram and attached the image to the project repo. You also want to make sure to reference it within the `API Docs` so that it is easily found towards the top of that doc. General syntax for referencing an image in .md syntax is: `![alt text](<path to image>)`

## Tasks:
- [x] Add DB Diagram
- [x] Create Tables
- [x] Add relevant attributes and constraints
- [x] Add associations and relationship types
- [x] Remove aggregate data
- [x] Handle preview images
- [x] account for hashed password and length sizes

# Deadline:

Please complete the API docs and DBDiagram tasks by EOD on Monday May, 13th. We are looking to get these documents finalized so we can move forward to the next phase of the project life cycle the following day.

**Comment by AnthonyBronca** [comment]
For Database Diagram, we do not want to have an aggregate data on the tables.

Please review:

- [x] Remove Aggregate data from the table/s
